version: '3.8'

services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - webnet

  backend:
    build: ./backend
    image: elcardbattlebackend:latest  
    container_name: ecb-backend
    restart: always
    networks:
      - webnet
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - FRONTEND_URL=https://ecbgame.bieda.it

  frontend:
    build: ./frontend
    image: elcardbattlefrontend:latest 
    container_name: ecb-frontend
    restart: always
    networks:
      - webnet
    environment:
      - NEXT_PUBLIC_BACKEND_URL=https://apiecb.bieda.it

networks:
  webnet:
    driver: bridge